apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-service-deployment
  labels:
    app: gate-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gate-service
  template:
    metadata:
      labels:
        app: gate-service
    spec:
      containers:
      - name: gate-service-container
        image: "132464628555.dkr.ecr.ap-northeast-2.amazonaws.com/kubepay/kubepay:gate"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
