apiVersion: v1
kind: Service
metadata:
  name: gate-service-service
  annotations:
    # AWS Classic Load Balancer를 사용하여 빠른 배포를 유도
    service.beta.kubernetes.io/aws-load-balancer-type: classic
spec:
  selector:
    app: gate-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # 외부에서 접근 가능하도록 LoadBalancer 타입 사용
